[package]
name = "rpn-calculator"
authors = [ "Camden Dixie O'Brien <cobrien@witekio.com>" ]
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.1"
embedded-hal = "0.2.7"
panic-halt = "0.2.0"

[dependencies.stm32f4xx-hal]
version = "0.13.2"
features = [ "stm32f407" ]
